### ISSUE TITLE
Cannot download Wikimedia commons dataset

### ISSUE THREAD

**Issue by kcsmta** [ialab-puc/VisualRecSys-Tutorial-IUI2021#9]
I run the code in `colabnotebooks/IUI_Tutorial_Feature_extraction.ipynb`, and unzipping the file raises this error:
```
[wikimedia_recsys.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of wikimedia_recsys.zip or
        wikimedia_recsys.zip.zip, and cannot find wikimedia_recsys.zip.ZIP, period.
```

How can I fix this? It seems the error of the zip file

**Comment by aaossa** [comment]
Hi @kcsmta , could you try this command instead of the whole first code cell? Please let me know if it works:

```
!gdown 1rXRT4Pa1opD_3koIQ2uvImjBlACcdC6R
```

**Comment by kcsmta** [comment]
Thank you for getting back to me. I confirm that the new command works perfectly. I just created a pull request that updates the dataset's download command. Could you take a look and update the repo?

**Comment by firatoncel** [comment]
Hi,

Download link is not working, can you check?
